### ISSUE TITLE
@OneToMany관계에서 toString 설정시 lazy initializatiol error 발생 이슈

### ISSUE THREAD

**Issue by deokju** [cod2mance/pinstagram#16]
PostServiceImplTest 에서 테스트 돌리는 경우
Post 와 Media 사이에 오류가 발생함

**Comment by tov324** [comment]
`Object.toFormattedString()` 호출 시 발생
함수 수정 필요

**Comment by tov324** [comment]
엔티티에 toString() 오버라이드하지 말자. toString내에서 참조하는 필드의 lazy loading으로 인해 성능상의 문제가 생긴다. 
테스트할 때, 필요하면 임시적으로 toString 사용하거나 직접 필드를 참조하자.

- [참고](https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/)
