### ISSUE TITLE
스프링에서 application.properties 대신 application.yml을 선호하는 이유가 뭐임..

### ISSUE THREAD

**Issue by tov324** [cod2mance/pinstagram#19]
to @deokju

**Comment by deokju** [comment]
음 사실 나도 잘 몰라요 ㅋㅋㅋ
내가 느낀 차이점은 properties 파일보다 yml이 사용하기 쉽다는거야
그 근거는
1. properties는 접두사가 계속 반복 되는 반면에 yml은 계층적 구조를 가져서 보기가 더 편하고 사용하기도 더 쉽다라는거야.
2. 하나의 파일에 동일한 설정을 여러개 두고 profile로 나눠서 쓰는것이 가능(properties)는 불가능

그런데 사실 2번은 동일한 설정을 하나의 파일에 두고 쓰는것은 나는 맘에 안들어서(모르고 잘못 복붙하면 망)
나는 첫번째 이유만으로 충분한것 같아

내가 참고한 글인데 표로 잘 설명 되어 있으니 형도 한번 참고 혀봐요

https://www.geeksforgeeks.org/difference-between-yaml-yml-and-properties-file-in-java-springboot/
