### ISSUE TITLE
REST API Request, Response 객체 디자인

### ISSUE THREAD

**Issue by deokju** [cod2mance/pinstagram#31]
요청 응답 값에 대한 처리를 어디까지 할것인지 고민

**Comment by tov324** [comment]
이게 무슨 이슈였더라.. 기억이 잘 안나네..

암튼 비즈니스 로직을 표현하는 `Entity` 클래스와, 통신 입출력을 담당하는 `Request`/`Response` 클래스는  완벽히 분리해야한다고 생각함 (몇가지 속성이 겹치더라도..) 

서로 다른 레이어에서 다른 일을 하는 클래스끼리 내용이 비슷하다는 이유로, 하나의 클래스로 합치거나 서로 재활용하지말고, 차라리 복사를 편하게 해주는 헬퍼메서드를 요청/응답 객체에 추가해도 좋을 듯..

예를 들어 컨트롤러가 PostCreateRequest와 PostCreatteResponse를 `생성`하는 책임과 `변환`(PostCreateRequest->Post, Post->PostCreateResponse) 하는 책임을 다 수행하고.. 서비스레이어로 넘길때는 순수한 Entity(비즈니스 객체)를 넘겨야 할 것으로 보임. 그 이후 서비스 레이어는 엔티티 객체와 비즈니스 로직 처리에만 집중하고.. 

정리하자면..

Request/Response 객체와 엔티티 객체는 분리되야 하며, 각 레이어의 책임은 다음과 같지 않을까 생각해본다.

1. 컨트롤러 책임
- 요청 객체 파싱, 유효성 검사, 모델 객체로 변환하여 서비스로 넘김 (유효성 검사와 변환 기능은는 Request객체에서 메서드로 제공해줘도 좋을듯)
- 서비스에서 받은 모델객체를 응답객체로 변환하여 반환 (이 때도 역시 변환 기능은 Response객체가 해도 좋을 듯)

2. 서비스 책임
- 모델(Entity)객체에 대한 유효성 검증
- 비즈니스 로직 처리

**Comment by tov324** [comment]
https://www.baeldung.com/java-dto-pattern

이렇게 DTO와 모델사이를 연결해주는 매퍼를 두는 방식도 좋을 듯!

**Comment by tov324** [comment]
DTO <-> Entity 매핑 방식

1. [spring way](https://medium.com/@a.adendrata/converting-dto-and-entity-c24cba9cef4)
2. [mapper library: mapstruct[(https://mapstruct.org/)
