### ISSUE TITLE
DTO<->Entity 매퍼 구성

### ISSUE THREAD

**Issue by tov324** [cod2mance/pinstagram#57]
- mapstruct 사용
- dto, entity 내부가 아닌 별도의 매퍼클래스 작성
   (dto가 entity를 알 필요도, entity가 dto를 알 필요도 없다.)

**Comment by deokju** [comment]
조금 더 정보가 필요합니다.
mapstruct라니?

**Comment by tov324** [comment]
오브젝트간의 속성매핑을 위해 자바에서는 mapstruct나 modelmapper를 많이쓰는데
mapstruct를 조금더추천하는거 같더라구..
아직 직접 보지는 않음

**Comment by tov324** [comment]
https://www.baeldung.com/mapstruct

**Comment by deokju** [comment]
오키오키
진짜 벨덩은 없는게 없네 ㅋㅋㅋ

**Comment by deokju** [comment]
한글 자료도 참고로 읽을만한거 찾았어
https://www.skyer9.pe.kr/wordpress/?p=1596

**Comment by tov324** [comment]
굿~ 한번 봐볼게

**Comment by tov324** [comment]
mapstruct로 진행하기로 함
