### ISSUE TITLE
Rest API 디자인

### ISSUE THREAD

**Issue by tov324** [cod2mance/pinstagram#59]
API 개발 시점에 API 문서 작성 환경이 구성되어 있어야한다.

그리고 개발과 API 문서화를 동시에 해야한다.

그래야 그.나.마 문서화를 별탈없이 진행할 수 있다. 나중에 하려면 잘 안하고 까먹기 일쑤다

- API 문서 명세는 OpenAPI 방식을 사용한다.
- Swagger와 RestDocs을 활용한다.
- [Swagger Editor](https://swagger.io/tools/swagger-editor/)

**Comment by tov324** [comment]
핀스타그램의 RestAPI 스펙을 아래 사진처럼 디자인해서 문서로 만들어줘.

편집은 [Swagger Editor](https://swagger.io/tools/swagger-editor/)를 사용하면 될 것 같은데, 더 좋은게 있으면 그걸 써도 되고~

### 참고

<img width="562" alt="Screen Shot 2021-11-19 at 11 33 29 AM" src="https://user-images.githubusercontent.com/87758094/142555092-8f3f5dc3-9429-4749-a9c4-8f8f4814cc52.png">

- [데모](https://editor.swagger.io/?_ga=2.210868503.361591408.1637289174-2096315127.1636964261)

**Comment by tov324** [comment]
@deokju 

오늘 작업했던 문서 좀 올려줘. 참고해서 나도 같이 작업하게!

**Comment by deokju** [comment]
openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pinstagram/basic/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://staging.pinstagram.wetov.io/
info:
  description: pinstagram base API
  version: "1.0.0"
  title: pinstagram base API
  contact:
    email: deokju.kim@kakao.com
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /post:
    post:
      summary: save post
      description: 
        핀스타 그램 포스트 저장 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                caption:
                  type: string    
      responses:
        '200':
          description: post가 정상적으로 등록되면 등록된 postId를 리턴한다
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: string    
        '400':
          description: bad input parameter
  /post/{postId}:
     get:
       summary: postId에 해당하는 post를 리턴한다.
       parameters:
        - name: postId
          in: path
          required: true
          description: post마다 부여 된 고유 아이디
          schema:
            type: string
            format: 'hashedId'
       responses:
         '200':
           description: post 조회 성공
           content:
             application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      post:
                        $ref: '#/components/schemas/Post'
                  
                                          

components:
  schemas:
    Post:
      type: object
      properties:
        postId:
          type: string
          description: hashed PostId.
        caption:
          type: string
          description: post 글 내용
        isReplyEnabled:
          type: boolean
          description: 댓글 허용 여부
        createdAt:
          type: string
          description: post 등록 날짜 시간
          example: '2021-12-10 14:28:000'
        updatedAt:
          type: string
          description: 가장 최근 수정 날짜 시간
          example: '2021-12-10 14:28:000'

**Comment by deokju** [comment]
`openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pinstagram/basic/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://staging.pinstagram.wetov.io/
info:
  description: pinstagram base API
  version: "1.0.0"
  title: pinstagram base API
  contact:
    email: deokju.kim@kakao.com
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /post:
    post:
      summary: save post
      description: 
        핀스타 그램 포스트 저장 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                caption:
                  type: string    
      responses:
        '200':
          description: post가 정상적으로 등록되면 등록된 postId를 리턴한다
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: string    
        '400':
          description: bad input parameter
  /post/{postId}:
     get:
       summary: postId에 해당하는 post를 리턴한다.
       parameters:
        - name: postId
          in: path
          required: true
          description: post마다 부여 된 고유 아이디
          schema:
            type: string
            format: 'hashedId'
       responses:
         '200':
           description: post 조회 성공
           content:
             application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      post:
                        $ref: '#/components/schemas/Post'
                  
                                          

components:
  schemas:
    Post:
      type: object
      properties:
        postId:
          type: string
          description: hashed PostId.
        caption:
          type: string
          description: post 글 내용
        isReplyEnabled:
          type: boolean
          description: 댓글 허용 여부
        createdAt:
          type: string
          description: post 등록 날짜 시간
          example: '2021-12-10 14:28:000'
        updatedAt:
          type: string
          description: 가장 최근 수정 날짜 시간
          example: '2021-12-10 14:28:000'`

**Comment by deokju** [comment]
형 이렇게 주면 도움이 되려나

openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pinstagram/basic/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://staging.pinstagram.wetov.io/
info:
  description: pinstagram base API
  version: "1.0.0"
  title: pinstagram base API
  contact:
    email: deokju.kim@kakao.com
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /post:
    post:
      summary: save post
      description: 
        핀스타 그램 포스트 저장 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                caption:
                  type: string    
      responses:
        '200':
          description: post가 정상적으로 등록되면 등록된 postId를 리턴한다
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: string    
        '400':
          description: bad input parameter
  /post/{postId}:
     get:
       summary: postId에 해당하는 post를 리턴한다.
       parameters:
        - name: postId
          in: path
          required: true
          description: post마다 부여 된 고유 아이디
          schema:
            type: string
            format: 'hashedId'
       responses:
         '200':
           description: post 조회 성공
           content:
             application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      post:
                        $ref: '#/components/schemas/Post'
                  
                                          

components:
  schemas:
    Post:
      type: object
      properties:
        postId:
          type: string
          description: hashed PostId.
        caption:
          type: string
          description: post 글 내용
        isReplyEnabled:
          type: boolean
          description: 댓글 허용 여부
        createdAt:
          type: string
          description: post 등록 날짜 시간
          example: '2021-12-10 14:28:000'
        updatedAt:
          type: string
          description: 가장 최근 수정 날짜 시간
          example: '2021-12-10 14:28:000'

**Comment by tov324** [comment]
ㅇㅋㅇㅋ 참고해서 내가 정리해서 다시 올릴게

**Comment by tov324** [comment]
REST API 문서 관련해서 읽어볼만 한 것들

- [Documenting APIs: A guide for technical writers and engineers](https://idratherbewriting.com/learnapidoc/#from-practice-to-documentation)
- [Rest API Documentation and Client Generation With OpenAPI](https://dzone.com/articles/rest-api-documentation-and-client-generation-with)
- [Documenting REST APIs: 5 Best Tips & Strategies for 2021](https://hevodata.com/learn/documenting-rest-apis/)

**Comment by tov324** [comment]
<img width="730" alt="Screen Shot 2021-11-22 at 1 54 49 PM" src="https://user-images.githubusercontent.com/87758094/142803137-f134ddd4-71cf-43a4-a579-faeaaad1d624.png">

2019년 기준 API 선호도 조사 내용..

OAS는 뭐지..

**Comment by tov324** [comment]
각 회사가 API 문서를 어떤 방식으로 개발하는지에 대한 조사

<img width="713" alt="Screen Shot 2021-11-22 at 2 12 18 PM" src="https://user-images.githubusercontent.com/87758094/142804577-8ba85b0f-8c38-4619-8cb9-94506f263ecc.png">

**Comment by tov324** [comment]
개꿀 정보 - 2020 API 트렌드 조사

https://idratherbewriting.com/learnapidoc/slides/devdoctrends_results.html#/

**Comment by tov324** [comment]
## Post

### Post:Create

URL

- `POST` /posts

Request

```json
{
  "caption": "본문",
  "is_reply_enabled": true,
  "media_upload_urls": [
    "https://s3.com/dif92jf12",
    ...
  ] 
}
```

Response

```json

```

Status

- success: 200
- bad request: 400
- resource not found: 404

### Post:List

URL

- `GET` /posts

Paging/Sorting/Search

- 

Request

```json

```

Response

```json
{
  "data": [{
    "id": "a217d2f713"
    "caption": "본문",
    "is_reply_enabled": true,
    "comment_count": 1,
    "created_at": "20210923T130928Z",
    "updated_at": "20210923T130928Z",
  }, {
     "id": "327e30fc87"
    "caption": "본문",
    "is_reply_enabled": true,
    "comment_count": 3,
    "created_at": "20210923T130928Z",
    "updated_at": "20210923T130928Z",
  }, {
    ...
  }],
  "total_count": 122,
  "count_per_page": 50
  "page": 2,
}
```

status

- 동일

### Post:Read

URL

- `GET` /posts/ae872c7b17

Request

```json

```

Response

```json
{
  "data": {
    "id": "ae872c7b17"
    "caption": "본문",
    "is_reply_enabled": true,
    "comment_count": 1,
    "created_at": "20210923T130928Z",
    "updated_at": "20210923T130928Z",
  }
}
```

Status

- 동일

### Post:Update

URL

- `PUT` /posts/ae872c7b17

Request

```json
{
  "id": "ae872c7b17"
  "caption": "수정된 본문",
  "is_reply_enabled": true,
}
```

Response

```json
{
  "data": {
    "id": "ae872c7b17"
    "caption": "수정된 본문",
    "is_reply_enabled": true,
    "comment_count": 1,
    "created_at": "20210923T130928Z",
    "updated_at": "20210923T180928Z",
  }
}
```

Status

- 동일

### Post:Delete

URL

- `DELETE` /posts/ae872c7b17

Request

```json

```

Response

```json
{
  "data": {
    "id": "ae872c7b17"
    "caption": "수정된 본문",
    "is_reply_enabled": true,
    "comment_count": 1,
    "created_at": "20210923T130928Z",
    "updated_at": "20210923T180928Z",
  }
}
```

Status

- 동일

**Comment by tov324** [comment]
OpenAPI 대신 Spring REST Docs로 진행 (애노테이션이 따로 필요없고, 테스트 코드로 문서 구현)

관련 이슈  #72
