### ISSUE TITLE
JPA 구성연습 및 학습

### ISSUE THREAD

**Issue by deokju** [cod2mance/pinstagram#76]
https://dev.mysql.com/doc/employee/en/sakila-structure.html
https://github.com/datacharmer/test_db

![image](https://user-images.githubusercontent.com/16514143/143735537-1a4eeeef-d2a2-4dc3-8943-b78f62fef700.png)

**Comment by tov324** [comment]
별도의 저장소에서 진행 

- https://github.com/cod2mance/jpa-employees/issues/1
